apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-config
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{- if $val }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}

