# Default values for microservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceType: ""
resources: {}

images:
  user-service: giacomoromagnoli4/user-service:latest
  friendship-service: giacomoromagnoli4/friendship-service:latest
  content-service: giacomoromagnoli4/content-service:latest
  api-gateway: giacomoromagnoli4/api-gateway:latest
  notification-service: giacomoromagnoli4/notification-service:latest

databaseNames:
  user-service: user
  friendship-service: friendship
  content-service: content

urls:
  user-service: user-service-microservice
  friendship-service: friendship-service-microservice
  content-service: content-service-microservice

image:
  pullPolicy: IfNotPresent

env:
  DB_HOST: mysql-cluster
  DB_PORT: 3306
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  KAFKA_HOST: kafka
  KAFKA_PORT: 9092

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /ready
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
