version: '3.8'

services:
  user-sql-db:
    image: user-sql-db:latest
    container_name: user-sql-db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2m
      timeout: 20s
      retries: 5
      start_period: 1m
      start_interval: 10s
    networks:
      - app-network

  user-service:
    image: user-service:latest
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      user-sql-db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge