name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on specified branches
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

  # Allows the run of this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # runs various CI steps like build, test, test coverage
  build-and-test:
    strategy:
      # defines a matrix of OS, languages and versions to check whether it works on each possible combination of them
      matrix:
        # disables macOS and windows to execute tests with docker
        os:
          - ubuntu-24.04
        #          - macos-14
        #          - windows-2022
        java-version: [17, 21]
        java-distribution: [corretto, temurin]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ matrix.java-version }}-${{ matrix.java-distribution }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # we chose this action because it already contains several CI steps we needed, like 'build' 'test' and 'test coverage'
      - name: Build using Gradle
        uses: DanySK/build-check-deploy-gradle-action@3.5.25
        with:
          pre-build-command: |
            echo -n "${{ secrets.DB_PASSWORD }}" > db-password.txt
            echo -n "${{ secrets.DB_ROOT_PASSWORD }}" > db-root-password.txt
          java-version: ${{ matrix.java-version }}
          java-distribution: ${{ matrix.java-distribution }}
          should-run-codecov: false
          retries-on-failure: 3

  publish-docker-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - "friendship-service"
          - "content-service"
          - "user-service"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build service ${{ matrix.service }}
        uses: DanySK/build-check-deploy-gradle-action@3.7.0
        with:
          should-run-codecov: false
          build-command: |
            if [ "${{ matrix.service }}" == "content-service" ]; then
            ./gradlew :${{ matrix.service }}:compileTypescript
            else
            ./gradlew :${{ matrix.service }}:assemble
            fi
          check-command: ":"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: true
          progress: plain
          tags: |
            marcofontana17/social-network-${{ matrix.service }}:latest
            marcofontana17/social-network-${{ matrix.service }}:${{ github.sha }}
